

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Currency : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Currency entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Currency()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Currency(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Currency> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Currency.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Currency_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Currency_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Currency.DetailsClass.GetValue(this, global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Currency.DetailsClass.SetValue(this, global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Currency.DetailsClass.GetValue(this, global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Currency.DetailsClass.SetValue(this, global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.Currency.DetailsClass.GetValue(this, global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.Currency.DetailsClass.SetValue(this, global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal CurrentRate
        {
            get
            {
                return global::LightSwitchApplication.Currency.DetailsClass.GetValue(this, global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.CurrentRate);
            }
            set
            {
                global::LightSwitchApplication.Currency.DetailsClass.SetValue(this, global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.CurrentRate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CurrentRate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CurrentRate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CurrentRate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Proposal> Proposals
        {
            get
            {
                return global::LightSwitchApplication.Currency.DetailsClass.GetValue(this, global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.Proposals);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Proposal> ProposalsQuery
        {
            get
            {
                return global::LightSwitchApplication.Currency.DetailsClass.GetQuery(this, global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.Proposals);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Currency,
                global::LightSwitchApplication.Currency.DetailsClass,
                global::LightSwitchApplication.Currency.DetailsClass.IImplementation,
                global::LightSwitchApplication.Currency.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass>.Entry
                __CurrencyEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass>.Entry(
                    global::LightSwitchApplication.Currency.DetailsClass.__Currency_CreateNew,
                    global::LightSwitchApplication.Currency.DetailsClass.__Currency_Created,
                    global::LightSwitchApplication.Currency.DetailsClass.__Currency_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Currency __Currency_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Currency> es)
            {
                return new global::LightSwitchApplication.Currency(es);
            }
            private static void __Currency_Created(global::LightSwitchApplication.Currency e)
            {
                e.Currency_Created();
            }
            private static bool __Currency_AllowSaveWithErrors(global::LightSwitchApplication.Currency e)
            {
                bool result = false;
                e.Currency_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Currency.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, decimal> CurrentRate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.CurrentRate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, global::LightSwitchApplication.Proposal> Proposals
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.Proposals) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, global::LightSwitchApplication.Proposal>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string Name { get; set; }
                new decimal CurrentRate { get; set; }
                new global::System.Collections.IEnumerable Proposals { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Currency.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, int>.Data> c, global::LightSwitchApplication.Currency.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Currency e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Currency e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Currency.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Currency.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Currency e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Currency.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Currency.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Currency e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Currency e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Currency.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Currency.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Currency e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Currency.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, string>.Data> c, global::LightSwitchApplication.Currency.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.Currency e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.Currency e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.Currency.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.Currency.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.Currency e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, decimal>.Entry
                    CurrentRate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, decimal>.Entry(
                        "CurrentRate",
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._CurrentRate_Stub,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._CurrentRate_ComputeIsReadOnly,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._CurrentRate_Validate,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._CurrentRate_GetImplementationValue,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._CurrentRate_SetImplementationValue,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._CurrentRate_OnValueChanged);
                private static void _CurrentRate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Currency.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.Currency.DetailsClass d, object sf)
                {
                    c(d, ref d._CurrentRate, sf);
                }
                private static bool _CurrentRate_ComputeIsReadOnly(global::LightSwitchApplication.Currency e)
                {
                    bool result = false;
                    e.CurrentRate_IsReadOnly(ref result);
                    return result;
                }
                private static void _CurrentRate_Validate(global::LightSwitchApplication.Currency e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CurrentRate_Validate(r);
                }
                private static decimal _CurrentRate_GetImplementationValue(global::LightSwitchApplication.Currency.DetailsClass d)
                {
                    return d.ImplementationEntity.CurrentRate;
                }
                private static void _CurrentRate_SetImplementationValue(global::LightSwitchApplication.Currency.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.CurrentRate = v;
                }
                private static void _CurrentRate_OnValueChanged(global::LightSwitchApplication.Currency e)
                {
                    e.CurrentRate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, global::LightSwitchApplication.Proposal>.Entry
                    Proposals = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, global::LightSwitchApplication.Proposal>.Entry(
                        "Proposals",
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._Proposals_Stub,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._Proposals_GetReferencedEntities,
                        global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties._Proposals_GetEntityCollection);
                private static void _Proposals_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Currency.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, global::LightSwitchApplication.Proposal>.Data> c, global::LightSwitchApplication.Currency.DetailsClass d, object sf)
                {
                    c(d, ref d._Proposals, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Proposal> _Proposals_GetReferencedEntities(global::LightSwitchApplication.Currency.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass>(global::LightSwitchApplication.Currency.DetailsClass.PropertySetProperties.Proposals, ref d._Proposals);
                }
                private static global::System.Collections.IEnumerable _Proposals_GetEntityCollection(global::LightSwitchApplication.Currency.DetailsClass d)
                {
                    return d.ImplementationEntity.Proposals;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, decimal>.Data _CurrentRate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass, global::LightSwitchApplication.Proposal>.Data _Proposals;
            
        }
    
        #endregion
    }
    
    #endregion
}
