

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Proposal : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Proposal entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Proposal()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Proposal(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Proposal> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Proposal.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Proposal_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Proposal_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Proposal.DetailsClass.GetValue(this, global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Proposal.DetailsClass.SetValue(this, global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Proposal.DetailsClass.GetValue(this, global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Proposal.DetailsClass.SetValue(this, global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return global::LightSwitchApplication.Proposal.DetailsClass.GetValue(this, global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.CreateDate);
            }
            set
            {
                global::LightSwitchApplication.Proposal.DetailsClass.SetValue(this, global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.CreateDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal Price
        {
            get
            {
                return global::LightSwitchApplication.Proposal.DetailsClass.GetValue(this, global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Price);
            }
            set
            {
                global::LightSwitchApplication.Proposal.DetailsClass.SetValue(this, global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Price, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Price_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Price_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Price_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal ProposalDatePrice
        {
            get
            {
                return global::LightSwitchApplication.Proposal.DetailsClass.GetValue(this, global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.ProposalDatePrice);
            }
            set
            {
                global::LightSwitchApplication.Proposal.DetailsClass.SetValue(this, global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.ProposalDatePrice, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProposalDatePrice_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProposalDatePrice_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProposalDatePrice_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Asset Asset
        {
            get
            {
                return global::LightSwitchApplication.Proposal.DetailsClass.GetValue(this, global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Asset);
            }
            set
            {
                global::LightSwitchApplication.Proposal.DetailsClass.SetValue(this, global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Asset, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Asset_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Asset_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Asset_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Supplier Supplier
        {
            get
            {
                return global::LightSwitchApplication.Proposal.DetailsClass.GetValue(this, global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Supplier);
            }
            set
            {
                global::LightSwitchApplication.Proposal.DetailsClass.SetValue(this, global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Supplier, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Supplier_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Supplier_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Supplier_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Currency Currency
        {
            get
            {
                return global::LightSwitchApplication.Proposal.DetailsClass.GetValue(this, global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Currency);
            }
            set
            {
                global::LightSwitchApplication.Proposal.DetailsClass.SetValue(this, global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Currency, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Currency_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Currency_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Currency_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Proposal,
                global::LightSwitchApplication.Proposal.DetailsClass,
                global::LightSwitchApplication.Proposal.DetailsClass.IImplementation,
                global::LightSwitchApplication.Proposal.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass>.Entry
                __ProposalEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass>.Entry(
                    global::LightSwitchApplication.Proposal.DetailsClass.__Proposal_CreateNew,
                    global::LightSwitchApplication.Proposal.DetailsClass.__Proposal_Created,
                    global::LightSwitchApplication.Proposal.DetailsClass.__Proposal_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Proposal __Proposal_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Proposal> es)
            {
                return new global::LightSwitchApplication.Proposal(es);
            }
            private static void __Proposal_Created(global::LightSwitchApplication.Proposal e)
            {
                e.Proposal_Created();
            }
            private static bool __Proposal_AllowSaveWithErrors(global::LightSwitchApplication.Proposal e)
            {
                bool result = false;
                e.Proposal_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Proposal.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::System.DateTime> CreateDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.CreateDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, decimal> Price
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Price) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, decimal> ProposalDatePrice
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.ProposalDatePrice) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Asset> Asset
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Asset) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Asset>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Supplier> Supplier
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Supplier) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Supplier>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Currency> Currency
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Currency) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Currency>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new global::System.DateTime CreateDate { get; set; }
                new decimal Price { get; set; }
                new decimal ProposalDatePrice { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Asset { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Supplier { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Currency { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Proposal.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, int>.Data> c, global::LightSwitchApplication.Proposal.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Proposal e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Proposal e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Proposal e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Proposal.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Proposal.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Proposal e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Proposal e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Proposal e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::System.DateTime>.Entry
                    CreateDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::System.DateTime>.Entry(
                        "CreateDate",
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._CreateDate_Stub,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._CreateDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._CreateDate_Validate,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._CreateDate_GetImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._CreateDate_SetImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._CreateDate_OnValueChanged);
                private static void _CreateDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Proposal.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Proposal.DetailsClass d, object sf)
                {
                    c(d, ref d._CreateDate, sf);
                }
                private static bool _CreateDate_ComputeIsReadOnly(global::LightSwitchApplication.Proposal e)
                {
                    bool result = false;
                    e.CreateDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreateDate_Validate(global::LightSwitchApplication.Proposal e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreateDate_Validate(r);
                }
                private static global::System.DateTime _CreateDate_GetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d)
                {
                    return d.ImplementationEntity.CreateDate;
                }
                private static void _CreateDate_SetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.CreateDate = global::LightSwitchApplication.Proposal.DetailsClass.TruncateDate(v);
                }
                private static void _CreateDate_OnValueChanged(global::LightSwitchApplication.Proposal e)
                {
                    e.CreateDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, decimal>.Entry
                    Price = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, decimal>.Entry(
                        "Price",
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Price_Stub,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Price_ComputeIsReadOnly,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Price_Validate,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Price_GetImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Price_SetImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Price_OnValueChanged);
                private static void _Price_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Proposal.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.Proposal.DetailsClass d, object sf)
                {
                    c(d, ref d._Price, sf);
                }
                private static bool _Price_ComputeIsReadOnly(global::LightSwitchApplication.Proposal e)
                {
                    bool result = false;
                    e.Price_IsReadOnly(ref result);
                    return result;
                }
                private static void _Price_Validate(global::LightSwitchApplication.Proposal e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Price_Validate(r);
                }
                private static decimal _Price_GetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d)
                {
                    return d.ImplementationEntity.Price;
                }
                private static void _Price_SetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.Price = v;
                }
                private static void _Price_OnValueChanged(global::LightSwitchApplication.Proposal e)
                {
                    e.Price_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, decimal>.Entry
                    ProposalDatePrice = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, decimal>.Entry(
                        "ProposalDatePrice",
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._ProposalDatePrice_Stub,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._ProposalDatePrice_ComputeIsReadOnly,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._ProposalDatePrice_Validate,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._ProposalDatePrice_GetImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._ProposalDatePrice_SetImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._ProposalDatePrice_OnValueChanged);
                private static void _ProposalDatePrice_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Proposal.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.Proposal.DetailsClass d, object sf)
                {
                    c(d, ref d._ProposalDatePrice, sf);
                }
                private static bool _ProposalDatePrice_ComputeIsReadOnly(global::LightSwitchApplication.Proposal e)
                {
                    bool result = false;
                    e.ProposalDatePrice_IsReadOnly(ref result);
                    return result;
                }
                private static void _ProposalDatePrice_Validate(global::LightSwitchApplication.Proposal e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProposalDatePrice_Validate(r);
                }
                private static decimal _ProposalDatePrice_GetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d)
                {
                    return d.ImplementationEntity.ProposalDatePrice;
                }
                private static void _ProposalDatePrice_SetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.ProposalDatePrice = v;
                }
                private static void _ProposalDatePrice_OnValueChanged(global::LightSwitchApplication.Proposal e)
                {
                    e.ProposalDatePrice_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Asset>.Entry
                    Asset = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Asset>.Entry(
                        "Asset",
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Asset_Stub,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Asset_ComputeIsReadOnly,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Asset_Validate,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Asset_GetCoreImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Asset_GetImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Asset_SetImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Asset_Refresh,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Asset_OnValueChanged);
                private static void _Asset_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Proposal.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Asset>.Data> c, global::LightSwitchApplication.Proposal.DetailsClass d, object sf)
                {
                    c(d, ref d._Asset, sf);
                }
                private static bool _Asset_ComputeIsReadOnly(global::LightSwitchApplication.Proposal e)
                {
                    bool result = false;
                    e.Asset_IsReadOnly(ref result);
                    return result;
                }
                private static void _Asset_Validate(global::LightSwitchApplication.Proposal e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Asset_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Asset_GetCoreImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d)
                {
                    return d.ImplementationEntity.Asset;
                }
                private static global::LightSwitchApplication.Asset _Asset_GetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Asset, global::LightSwitchApplication.Asset.DetailsClass>(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Asset, ref d._Asset);
                }
                private static void _Asset_SetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d, global::LightSwitchApplication.Asset v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Asset, ref d._Asset, (i, ev) => i.Asset = ev, v);
                }
                private static void _Asset_Refresh(global::LightSwitchApplication.Proposal.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Asset, ref d._Asset);
                }
                private static void _Asset_OnValueChanged(global::LightSwitchApplication.Proposal e)
                {
                    e.Asset_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Supplier>.Entry
                    Supplier = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Supplier>.Entry(
                        "Supplier",
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Supplier_Stub,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Supplier_ComputeIsReadOnly,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Supplier_Validate,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Supplier_GetCoreImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Supplier_GetImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Supplier_SetImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Supplier_Refresh,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Supplier_OnValueChanged);
                private static void _Supplier_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Proposal.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Supplier>.Data> c, global::LightSwitchApplication.Proposal.DetailsClass d, object sf)
                {
                    c(d, ref d._Supplier, sf);
                }
                private static bool _Supplier_ComputeIsReadOnly(global::LightSwitchApplication.Proposal e)
                {
                    bool result = false;
                    e.Supplier_IsReadOnly(ref result);
                    return result;
                }
                private static void _Supplier_Validate(global::LightSwitchApplication.Proposal e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Supplier_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Supplier_GetCoreImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d)
                {
                    return d.ImplementationEntity.Supplier;
                }
                private static global::LightSwitchApplication.Supplier _Supplier_GetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Supplier, global::LightSwitchApplication.Supplier.DetailsClass>(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Supplier, ref d._Supplier);
                }
                private static void _Supplier_SetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d, global::LightSwitchApplication.Supplier v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Supplier, ref d._Supplier, (i, ev) => i.Supplier = ev, v);
                }
                private static void _Supplier_Refresh(global::LightSwitchApplication.Proposal.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Supplier, ref d._Supplier);
                }
                private static void _Supplier_OnValueChanged(global::LightSwitchApplication.Proposal e)
                {
                    e.Supplier_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Currency>.Entry
                    Currency = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Currency>.Entry(
                        "Currency",
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Currency_Stub,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Currency_ComputeIsReadOnly,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Currency_Validate,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Currency_GetCoreImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Currency_GetImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Currency_SetImplementationValue,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Currency_Refresh,
                        global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties._Currency_OnValueChanged);
                private static void _Currency_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Proposal.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Currency>.Data> c, global::LightSwitchApplication.Proposal.DetailsClass d, object sf)
                {
                    c(d, ref d._Currency, sf);
                }
                private static bool _Currency_ComputeIsReadOnly(global::LightSwitchApplication.Proposal e)
                {
                    bool result = false;
                    e.Currency_IsReadOnly(ref result);
                    return result;
                }
                private static void _Currency_Validate(global::LightSwitchApplication.Proposal e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Currency_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Currency_GetCoreImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d)
                {
                    return d.ImplementationEntity.Currency;
                }
                private static global::LightSwitchApplication.Currency _Currency_GetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Currency, global::LightSwitchApplication.Currency.DetailsClass>(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Currency, ref d._Currency);
                }
                private static void _Currency_SetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass d, global::LightSwitchApplication.Currency v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Currency, ref d._Currency, (i, ev) => i.Currency = ev, v);
                }
                private static void _Currency_Refresh(global::LightSwitchApplication.Proposal.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Proposal.DetailsClass.PropertySetProperties.Currency, ref d._Currency);
                }
                private static void _Currency_OnValueChanged(global::LightSwitchApplication.Proposal e)
                {
                    e.Currency_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::System.DateTime>.Data _CreateDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, decimal>.Data _Price;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, decimal>.Data _ProposalDatePrice;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Asset>.Data _Asset;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Supplier>.Data _Supplier;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Proposal, global::LightSwitchApplication.Proposal.DetailsClass, global::LightSwitchApplication.Currency>.Data _Currency;
            
        }
    
        #endregion
    }
    
    #endregion
}
